# Generated by Django 3.1.4 on 2020-12-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('building_type', models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial'), ('I', 'Industrial')], max_length=1, verbose_name='Building Type')),
                ('description', models.TextField(max_length=500, verbose_name='Description of services needed')),
                ('date', models.DateTimeField(verbose_name='Appointment Date')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
