# Generated by Django 3.1.4 on 2020-12-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=1, max_length=13, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
