# Generated by Django 3.1.4 on 2020-12-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201215_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='building_type',
            field=models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial'), ('I', 'Industrial')], max_length=1),
        ),
    ]
