# Generated by Django 3.1.4 on 2020-12-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='building_type',
            field=models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial'), ('I', 'Industrial')], max_length=1, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description of services needed'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Phone Number'),
        ),
    ]
